import "./globals.css";
import "@snake/ui/styles.css";
import { KeyboardContextProvider } from "@/contexts/keyboard-context";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <KeyboardContextProvider>{children}</KeyboardContextProvider>
      </body>
    </html>
  );
}
